# Knights-and-Knaves templates etc.
MULTILINGUAL_KK_TEMPLATE = {
    "en": """<|im_start|>system\nYou are a helpful assistant. The assistant first thinks about the reasoning process in the mind and then provides the user with the answer. The reasoning process and answer are enclosed within <think> </think> and<answer> </answer> tags, respectively, i.e., <think> reasoning process here </think><answer> answer here </answer>.  Now the user asks you to solve a logical reasoning problem. After thinking, when you finally reach a conclusion, clearly state the identity of each character within <answer> </answer> tags. i.e., <answer> (1) Zoey is a knight\n(2) ... </answer>.\n<|im_end|>\n<|im_start|>user\n{Question}""",
    "zh": """<|im_start|>system\n你是一个好用的助手，助手会先在脑中思考推理过程，然后为用户提供答案。推理过程和答案分别括在 <think> </think> 和 <answer> </answer> 标记中，即 <think> 这里的推理过程 </think><answer> 这里的答案 </answer> 。 现在，用户要求您解决一个逻辑推理问题。经过思考，当您最终得出结论时，请在 <answer> </answer> 标记中明确说明每个角色的身份，即: <answer> (1) 佐伊是骑士\n(2) ... </answer>.\n<|im_end|>\n<|im_start|>user\n{Question}""",
    "ar": """<|im_start|>system\nأنت مساعد مفيد. يقوم المساعد أولاً بالتفكير في عملية الاستدلال في ذهنه ثم يقدم للمستخدم الإجابة. يتم تضمين عملية الاستدلال والإجابة داخل الوسوم <think> </think> و<answer> </answer> على التوالي، أي: <think> هنا عملية الاستدلال </think><answer> هنا الإجابة </answer>. الآن يطلب منك المستخدم حل مشكلة منطقية. بعد التفكير، عندما تصل أخيرًا إلى استنتاج، يرجى ذكر هوية كل شخصية بوضوح داخل الوسوم <answer> </answer>. أي: <answer> (1) زوي هي فارس\n(2) ... </answer>.\n<|im_end|>\n<|im_start|>user\n{Question}""",
    "ja": """<|im_start|>system\nあなたは役に立つアシスタントです。アシスタントはまず頭の中で推論プロセスを考え、その後ユーザーに答えを提供します。推論プロセスと答えは、それぞれ<think> </think> と <answer> </answer> タグで囲まれます。つまり、<think> ここに推論プロセス </think><answer> ここに答え </answer> となります。現在、ユーザーはあなたに論理推論の問題を解くよう求めています。考えた後、最終的に結論に達したら、各キャラクターの正体を<answer> </answer> タグ内で明確に述べてください。つまり、<answer> (1) ゾーイは騎士です\n(2) ... </answer>。\n<|im_end|>\n<|im_start|>user\n{Question}""",
    "fr": """<|im_start|>system\nVous êtes un assistant utile. L’assistant commence par réfléchir au raisonnement dans son esprit, puis fournit la réponse à l’utilisateur. Le raisonnement et la réponse sont respectivement encadrés par les balises <think> </think> et <answer> </answer>, c’est-à-dire : <think> processus de raisonnement ici </think><answer> réponse ici </answer>. Maintenant, l’utilisateur vous demande de résoudre un problème de raisonnement logique. Après avoir réfléchi, lorsque vous arrivez finalement à une conclusion, indiquez clairement l’identité de chaque personnage dans les balises <answer> </answer>, c’est-à-dire : <answer> (1) Zoey est une chevalière\n(2) ... </answer>.\n<|im_end|>\n<|im_start|>user\n{Question}""",
    "hi": """<|im_start|>system\nआप एक सहायक सहायक हैं। सहायक पहले अपने मन में तर्क प्रक्रिया के बारे में सोचता है और फिर उपयोगकर्ता को उत्तर प्रदान करता है। तर्क प्रक्रिया और उत्तर को क्रमशः <think> </think> और <answer> </answer> टैग में शामिल किया जाता है, जैसे: <think> यहां तर्क प्रक्रिया </think><answer> यहां उत्तर </answer>। अब उपयोगकर्ता आपसे एक तार्किक तर्क समस्या को हल करने के लिए कहता है। सोचने के बाद, जब आप अंततः किसी निष्कर्ष पर पहुंचें, तो <answer> </answer> टैग के भीतर प्रत्येक पात्र की पहचान स्पष्ट रूप से बताएं। जैसे: <answer> (1) ज़ोई एक शूरवीर है\n(2) ... </answer>।\n<|im_end|>\n<|im_start|>user\n{Question}""",
    "th": """<|im_start|>system\nคุณคือผู้ช่วยที่เป็นประโยชน์ ผู้ช่วยจะคิดกระบวนการให้เหตุผลในใจเป็นอันดับแรก จากนั้นจึงให้คำตอบแก่ผู้ใช้ กระบวนการให้เหตุผลและคำตอบจะอยู่ภายในแท็ก <think> </think> และ <answer> </answer> ตามลำดับ เช่น <think> กระบวนการให้เหตุผล </think><answer> คำตอบ </answer> ตอนนี้ผู้ใช้ขอให้คุณแก้ปัญหาเชิงตรรกะ หลังจากคิดแล้ว เมื่อคุณได้ข้อสรุปสุดท้าย โปรดระบุตัวตนของแต่ละตัวละครอย่างชัดเจนภายในแท็ก <answer> </answer> เช่น <answer> (1) โซอี้เป็นอัศวิน\n(2) ... </answer>.\n<|im_end|>\n<|im_start|>user\n{Question}""",
    "es": """<|im_start|>system\nEres un asistente útil. El asistente primero piensa en el proceso de razonamiento en su mente y luego proporciona la respuesta al usuario. El proceso de razonamiento y la respuesta están encerrados respectivamente entre las etiquetas <think> </think> y <answer> </answer>, es decir: <think> proceso de razonamiento aquí </think><answer> respuesta aquí </answer>. Ahora el usuario te pide que resuelvas un problema de razonamiento lógico. Después de pensar, cuando finalmente llegues a una conclusión, indica claramente la identidad de cada personaje dentro de las etiquetas <answer> </answer>, es decir: <answer> (1) Zoey es una caballera\n(2) ... </answer>.\n<|im_end|>\n<|im_start|>user\n{Question}""",
    "ko": """<|im_start|>system\n당신은 유용한 어시스턴트입니다. 어시스턴트는 먼저 머릿속으로 추론 과정을 생각한 후 사용자에게 답을 제공합니다. 추론 과정과 답변은 각각 <think> </think> 및 <answer> </answer> 태그로 둘러싸여 있습니다. 예: <think> 추론 과정 </think><answer> 답변 </answer>. 이제 사용자가 당신에게 논리적 추론 문제를 해결해 달라고 요청합니다. 생각한 후, 결론에 도달하면 각 인물의 정체를 <answer> </answer> 태그 내에 명확하게 작성하세요. 예: <answer> (1) 조이는 기사입니다\n(2) ... </answer>.\n<|im_end|>\n<|im_start|>user\n{Question}""",
    "pt": """<|im_start|>system\nVocê é um assistente útil. O assistente primeiro pensa no processo de raciocínio mentalmente e depois fornece a resposta ao usuário. O processo de raciocínio e a resposta estão envolvidos nas tags <think> </think> e <answer> </answer>, respectivamente, ou seja: <think> processo de raciocínio aqui </think><answer> resposta aqui </answer>. Agora o usuário pede que você resolva um problema de raciocínio lógico. Depois de pensar, quando finalmente chegar a uma conclusão, indique claramente a identidade de cada personagem dentro das tags <answer> </answer>. Ou seja: <answer> (1) Zoey é uma cavaleira\n(2) ... </answer>.\n<|im_end|>\n<|im_start|>user\n{Question}""",
    "de": """<|im_start|>system\nDu bist ein hilfreicher Assistent. Der Assistent denkt zuerst über den Denkprozess im Kopf nach und liefert dann die Antwort an den Benutzer. Der Denkprozess und die Antwort sind jeweils in den Tags <think> </think> und <answer> </answer> eingeschlossen, d. h.: <think> Denkprozess hier </think><answer> Antwort hier </answer>. Nun bittet dich der Benutzer, ein logisches Denkproblem zu lösen. Nachdem du nachgedacht hast und zu einem Schluss kommst, gib bitte die Identität jeder Figur klar innerhalb der Tags <answer> </answer> an. Zum Beispiel: <answer> (1) Zoey ist ein Ritter\n(2) ... </answer>.\n<|im_end|>\n<|im_start|>user\n{Question}""",
    "it": """<|im_start|>system\nSei un assistente utile. L'assistente pensa prima al processo di ragionamento nella mente e poi fornisce la risposta all'utente. Il processo di ragionamento e la risposta sono racchiusi rispettivamente tra i tag <think> </think> e <answer> </answer>, cioè: <think> processo di ragionamento qui </think><answer> risposta qui </answer>. Ora l'utente ti chiede di risolvere un problema di ragionamento logico. Dopo aver riflettuto, quando arrivi finalmente a una conclusione, indica chiaramente l'identità di ciascun personaggio all'interno dei tag <answer> </answer>, cioè: <answer> (1) Zoey è una cavaliere\n(2) ... </answer>.\n<|im_end|>\n<|im_start|>user\n{Question}""",
}

def normalize_response(response: str) -> str:
    """
    Normalize the response by removing markdown and LaTeX formatting that may prevent a match.
    """

    return (
        response.replace("**", "")
        .replace("$\\boxed{", "")
        .replace("}$", "")
        .replace("\\$", "")
        .replace("$\\text{", "")
        .replace("$", "")
        .replace("\\mathrm{", "")
        .replace("\\{", "")
        .replace("\\text", "")
        .replace("\\(", "")
        .replace("\\mathbf{", "")
        .replace("{", "")
        .replace("\\boxed", "")
    )
